sudo: required
services:
  - docker

before_install:
  - docker build -t dtikhonov/multi-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dtikhonov/multi-client-test npm run test

after_success:
  - docker build -t dtikhonov/multi-client ./client
  - docker build -t dtikhonov/multi-nginx ./nginx
  - docker build -t dtikhonov/multi-server ./server
  - docker build -t dtikhonov/multi-worker ./worker
  # Log in into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to the Docker hub
  - docker push dtikhonov/multi-client
  - docker push dtikhonov/multi-nginx
  - docker push dtikhonov/multi-server
  - docker push dtikhonov/multi-worker

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-651416516786
  bucket_path: docker-multi
  on:
    branch: master